services:
    chromadb:
        image: chromadb/chroma
        ports:
            - "8000:8000"
        environment:
            CHROMA_SERVER_CORS_ALLOW_ORIGINS: '["*"]'
            # Optimize for low memory
            CHROMA_SERVER_HOST: "0.0.0.0"
            CHROMA_SERVER_HTTP_PORT: "8000"
        volumes:
            - chromadb_data:/chroma/chroma
        # Memory limits for t2.micro
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M
        # Restart policy
        restart: unless-stopped
        # Health check
        healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

volumes:
    chromadb_data:
