services:
    chromadb:
        image: chromadb/chroma
        ports:
            - "8000:8000"
        environment:
            CHROMA_SERVER_CORS_ALLOW_ORIGINS: '["*"]'
        volumes:
            - chromadb_data:/chroma/chroma

volumes:
    chromadb_data:
